autoInstallPeers: false
overrides:
  'vite@<=6.4.2': 6.4.3
  'minimatch@>=9.0.0 <9.0.7': 9.0.9

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
