autoInstallPeers: false
overrides:
  'minimatch@>=9.0.0 <9.0.7': 9.0.9

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true

minimumReleaseAgeExclude:
  - globals@17.7.0
  - vite@8.1.0
